// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjA3uVoxDm8wn3VD2P7fihWr3jQeugwqM',
    appId: '1:804094823022:android:f584db5d51feaa9073f47f',
    messagingSenderId: '804094823022',
    projectId: 'ctm-project-61362',
    storageBucket: 'ctm-project-61362.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIo5zGCqYqqLof5esxmmKUe5A5MnTTPqM',
    appId: '1:804094823022:ios:a7d6c60482ddb07d73f47f',
    messagingSenderId: '804094823022',
    projectId: 'ctm-project-61362',
    storageBucket: 'ctm-project-61362.firebasestorage.app',
    iosBundleId: 'com.chothongminh.merchant',
  );
  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyDjA3uVoxDm8wn3VD2P7fihWr3jQeugwqM',
  //   appId: '1:804094823022:android:133cb2d9a9b28f5f73f47f',
  //   messagingSenderId: '804094823022',
  //   projectId: 'ctm-project-61362',
  //   storageBucket: 'ctm-project-61362.firebasestorage.app',
  // );
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyCIo5zGCqYqqLof5esxmmKUe5A5MnTTPqM',
  //   appId: '1:804094823022:ios:8b61db50abbcbcf773f47f',
  //   messagingSenderId: '804094823022',
  //   projectId: 'ctm-project-61362',
  //   storageBucket: 'ctm-project-61362.firebasestorage.app',
  //   iosBundleId: 'com.chothongminh.merchant.dev',
  // );
}
